### PR TITLE
Add example notebooks to doc

### PR DESCRIPTION
**Pull request by arnaudon**
I just realised we can add notebooks in the doc!

### CODE REVIEW

**Comment by d-schindler** [comment]
Where can I read the Doc for this PR?

**Comment by arnaudon** [comment]
Checkout this PR, then run `tox -e docs` in it, and check the folder `pygenstability-doc/html` that was created next to the repo (not inside). You'll see `index.html` which you can open with your browser to see the doc as it will appear online.

**Comment by peach-lucien** [comment]
docs are compiling nicely. Did you just add the notebook directly to docs/source/examples folder, and it compiles in main doc?

**Comment by arnaudon** [comment]
you also need to refer to the file in: [docs/source/index.rst](https://github.com/barahona-research-group/PyGenStability/pull/61/files#diff-4eec6cec5f6fab1548b85433ea8ca81315ae165db4b7f84019f287df9015699f)

**Comment by peach-lucien** [comment]
Installed in a clean env and ran benchmarks and checks passed - seems good to me.

**Review by peach-lucien — APPROVED** [review]

**Comment by arnaudon** [comment]
Yeah, but we can make notebook better with explanations, like a doc page people can use to learn the package. I just tried to include  a notebook here ;)

**Review by d-schindler — COMMENTED** [review]
seems good to me, have merged for now, as it seemed like you were waiting for me to do this

**Comment by arnaudon** [comment]
nah, I said we need to improve the notebook we add in the doc ;) feel free to do it if you have time

**Comment by arnaudon** [comment]
no no, juste make another PR, np!

**Pull request merged**
