### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by d-schindler**
This PR is to improve the documentation.

### CODE REVIEW

**Comment by d-schindler** [comment]
I corrected some typos in the doc strings. The doc of the run function needs improvement, in particular the description of the return. Moreover, the docs for the different constructors should be improved, e.g. by adding the formulas in terms of "quality matrix" and "null model" explicitly. 

I also marked functions for internal use only with "_", so they won't appear in the documentation (I hope).

**Comment by arnaudon** [comment]
I tried to add more to the doc, and changed the style to furo, so it looks better, without overlapping text. @d-schindler , @peach-lucien have a look to spot any typos, etc... and then I'll merge.

**Comment by arnaudon** [comment]
Ah no, let's not rename this Constructor class, it will break to much stuff

**Comment by d-schindler** [comment]
Ok fine. Still working on typos etc. and incorporating references if you don't mind.

**Comment by arnaudon** [comment]
also let's not put references in the run docstring, they are already in the main entry page, this should be a more detailed explanation of the function, not the general overview

**Comment by arnaudon** [comment]
maybe add comments here for typos, I'll fix them, to prevent conflicts

**Comment by d-schindler** [comment]
But what about adding references to the different constructors?

**Comment by arnaudon** [comment]
we reference our paper in the main page, where we have all. Is it not enough?

**Comment by d-schindler** [comment]
these are the things I would change

- use either "generalised" or "generalized"
- replace "name of the quality constructor" with "name of the generalized modularity constructor"
- expand to "kwargs to pass to optimal scale selection, see https://barahona-research-group.github.io/PyGenStability/optimal_scales.html"

I understand that renaming Constructor to GenModularity might break to much for now, but I think that the name "Constructor" is really confusing. Actually, it provides the abstract class for generalized modularity. So if you don't want to rename, maybe you can still say it in the docstring of the class?

**Comment by d-schindler** [comment]
maybe we can still use a proper reference in "signed_modularity"? It's not cited in our paper

**Comment by arnaudon** [comment]
ok, done! for scale selection, it's a bit tight, I added a mention to the module with full docstring

**Comment by d-schindler** [comment]
One comment on the formula for the directed case, I think you actually implemented this (from Lambiotte 2014):

Screenshot from 2023-02-09 10-57-21

**Comment by d-schindler** [comment]
**important remark:** in constructors.py we still talk about "time", but we decided to use "scale" instead like in pygenstability.py. We need to be consistent about this.

**Comment by arnaudon** [comment]
> One comment on the formula for the directed case, I think you actually implemented this (from Lambiotte 2014):
> 
> Screenshot from 2023-02-09 10-57-21
> 
> which is different from what you wrote in the docstring, the indicator for the "dangling nodes" is missing

I copied your formula in the paper, I assumed you used the correct one. If you fix it in the paper I will update it, so it's consistent! I will fix the 'time/scale' now

**Comment by d-schindler** [comment]
fair enough, these should be the formulas for the directed case:

Quality matrix $F(t)=\Pi \exp\left(-\alpha L-\left(\frac{1-\alpha}{N}+\alpha \diag(a)\right)I\right)$, where $a$ denotes the vector of `dangling' nodes, i.e. $a_i=1$ if the out-degree $d_i=0$ and $a_i=0$ otherwise, $I$ denotes the identity matrix and $0\le \alpha < 1$ the damping factor, and associated null model $v_0=v_1=\pi$ given by the PageRank vector $\pi$.

**Comment by d-schindler** [comment]
**Important remark:** When you renamed "evaluate_NVI" to "_evaluate_NVI", you didn't apply this to all files. So e.g. multiscale_example.py is not working anymore. (This was the reason why I decided to not rename "evaluate_NVI" in my commit, also because it's handy to use outside as in the example.)

**Comment by arnaudon** [comment]
ah right, I reverted this and added a better docstring to this function. I also added the correct formula for the directed constructor.  It should be better now! I can merge tomorrow and update the doc, so we can see it live and spot the last issues!

**Comment by d-schindler** [comment]
Sounds good to me, I've already had a look at it and here are some comments:

- in the doc for evaluate_NVI, I think we should make sure that people understand that index_pair is only **one pair of two indices**?
- the doc for the directed constructor now contains some redundant information
- can we improve the doc for the signed constructor? the reference actually contains many versions of modularity and I'm not sure which one is implemented, so it would be good to provide quality matrix and null model again. Also "The scale only multiplies the quality matrix (this many not mean anything, use with care!)." doesn't sound very promising. If we don't know that it works, should we rather remove it from the first version until we have clear indications it works well?

**Comment by arnaudon** [comment]
good catch, I improved that!

**Comment by d-schindler** [comment]
great, you wrote "sstandard" though

**Comment by arnaudon** [comment]
jeez, fixed! good to merge and I update the doc online?

**Comment by d-schindler** [comment]
Yes :) thanks for updating!

**Comment by arnaudon** [comment]
Voila! https://barahona-research-group.github.io/PyGenStability/

**Pull request merged**
