### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by arnaudon** [comment]
Just need to add leiden tests to increase cov back to 100 once leiden PR is merged/released

**Comment by d-schindler** [comment]
I used this branch to make a small change for the plotting: I discovered that we often have white regions on the diagonal of the NVI(t,t^\prime) heatmap when the NVI is 0 but actually it should be dark in our colour scheme, so I changed the "extend" of the contour plot to "min".

**Comment by arnaudon** [comment]
ah sorry, I thought this was leiden branch, it's fine here indeed! Feel free to improve stuff here as well!

**Comment by peach-lucien** [comment]
did we decide on whether we want to merge these examples into main? They are not quick to compute despite my best efforts to compressing them considerably. If so, we will want to add these examples into the docs.

**Comment by d-schindler** [comment]
I thought we wanted to pre-compute the examples, and provide the results as files that are then just read in the notebooks?

**Pull request merged**
