### PR TITLE
Signed combinatorial constructor

### PR DESCRIPTION
**Pull request by d-schindler**
This PR is to implement a constructor based on the signed combinatorial Laplacian, see: https://github.com/michaelschaub/generalizedLouvain/blob/master/MATLAB/quality_functions/louvain_signedLap.m

### CODE REVIEW

**Comment by d-schindler** [comment]
I'm confused about the null model, in https://github.com/michaelschaub/generalizedLouvain/blob/1d3e73b30ec2ce8edac44a300f5a767050048230/MATLAB/quality_functions/louvain_signedLap.m#L49 it seems to depend on the scale.

We should also create an example notebook for signed graphs.

**Comment by d-schindler** [comment]
I implemented `signed_combinatorial` now with 0 as the null model, as suggested by Michael.

I also added the signed network from the Harari data as an example and applied both `signed_modularity` and `signed_combinatorial` constructors. They seem to work and the clusters seem to correspond to the ones in the PRE paper according to the labels, but maybe @arnaudon can double-check?

**Comment by d-schindler** [comment]
I think this is ready to merge after your checks, @arnaudon

**Comment by d-schindler** [comment]
@arnaudon , is there anything else you want me to do here?

**Review by arnaudon — APPROVED** [review]

**Pull request merged**
