### PR TITLE
Update cli

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by d-schindler** [comment]
Are we still missing the arguments for constructor_kwargs and method for matrix exponential?

**Review by d-schindler — CHANGES_REQUESTED** [review]
See comment above

**Comment by arnaudon** [comment]
yes, the kwargs are a bit difficult to pass via command line, I thought to only allow users to access these via python scripts

**Comment by d-schindler** [comment]
And what about `exp_comp_mode`?

**Comment by arnaudon** [comment]
done!

**Pull request merged**
