### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by d-schindler**
This PR is to make some changes on our presentation of examples.

### CODE REVIEW

**Comment by d-schindler** [comment]
I used the multiscale example to show in the docs. It would be nice to import multiscale_example.create_graph somehow from the /examples folder but I couldn't do it (import didn't work after adding an __init__ to examples). Could somebody else have a look at this? - but also not essential

**Comment by d-schindler** [comment]
And for the single-scale SBM I now used clusters of the same size which produces nice and easy results where we recover the only partition correctly

**Comment by d-schindler** [comment]
I also realised that some parts of the documentation are not up to date with the code and docstrings, e.g. here: https://barahona-research-group.github.io/PyGenStability/optimal_scales.html

**Comment by d-schindler** [comment]
I updated the parameters for the scale selection to make it more robust to noise (kernel size depends on n_scales now). Using these parameters I re-run our examples and things look much better now. I also tweaked min_scale in the multiscale example such that we don't get the partition of singletons. This makes the plot clearer and we need to explain less in the paper.

There was also an issue with Example 3 on my side. Although I have networkx version >= 2.4 as defined in the requirements, I get "module networkx has no attribute to_scipy_sparse_array". So I rewrote the code slightly.

**Comment by d-schindler** [comment]
I also reran the real examples with the updated scale selection parameters and things look much better.

This branch is now ready to be merged.

**Comment by d-schindler** [comment]
@arnaudon, do you still want to merge for now?

**Comment by arnaudon** [comment]
@d-schindler , anything left to do from your comments above? Sorry, I was behind on this one...

**Pull request merged**
