### PR TITLE
update installation in readme

### PR DESCRIPTION
**Pull request by d-schindler**

### CODE REVIEW

**Comment by d-schindler** [comment]
What happened to the contrib module? Is it not an extra anymore?

**Comment by arnaudon** [comment]
maybe let's keep both installations, clone and pypi.

**Comment by arnaudon** [comment]
> What happened to the contrib module? Is it not an extra anymore?

it is installed by default in the main package, as it is not a dependency

**Comment by d-schindler** [comment]
> maybe let's keep both installations, clone and pypi.

But then the section get's very long, especially when we go through all the extras again.

**Comment by d-schindler** [comment]
I added a (slightly modified) description of installation via cloning, have a look!

**Comment by d-schindler** [comment]
@arnaudon , can we merge this?

**Comment by arnaudon** [comment]
Sure, it looks good!

**Pull request merged**
