### PR TITLE
Add leiden solver

### PR DESCRIPTION
**Pull request by arnaudon**
This PR adds leiden method to maximize generalized modularity, following the trick of V. Traag explained here: https://github.com/vtraag/leidenalg/pull/109#issuecomment-1283963065

### CODE REVIEW

**Comment by peach-lucien** [comment]
Is this now ready for reviewing?

**Comment by d-schindler** [comment]
I guess we have to wait until Generalized Modularity is integrated in the Leiden package?

**Comment by arnaudon** [comment]
Ah yes, sorry, I didn't reply here. Let's wait a little here indeed.

**Comment by d-schindler** [comment]
Should I review now?

**Comment by peach-lucien** [comment]
I believe we are still waiting on whether traag will merge the small fix on leiden --> https://github.com/vtraag/leidenalg/pulls

**Comment by arnaudon** [comment]
But you can review, yes, if you find anything weird, please add comments!

**Comment by d-schindler** [comment]
I think we need to wait until a new Leidenalg version is released that contains the 'correct_self_loops' argument?

**Review by d-schindler — APPROVED** [review]
Everything seems fine and the code works on my side.

**Comment by arnaudon** [comment]
Ok, great! I'll fix the tests tonight and merge!

**Comment by d-schindler** [comment]
Amazing! I'm looking forward to finally use Leiden for MS analysis and excited to see how things change.

**Comment by d-schindler** [comment]
what remains open to do here? I'm waiting for this PR to be merged before I start with updating the scale selection..

**Comment by arnaudon** [comment]
I'm struggling with the tests... but start a new PR on top of this one, (you create a new branch when you are on this one), we'll sort it out later! I will resume the fight later today!

**Pull request merged**
