### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by d-schindler**
This PR is to update the documentation including the README

### CODE REVIEW

**Comment by peach-lucien** [comment]
the readme still needs the references added before merging into master I believe? or remove them from the text.

**Comment by d-schindler** [comment]
I added the references and code snippets for specifying Leiden and plotting optimal partitions in the workflow

**Comment by d-schindler** [comment]
I also changed all "vi" and "variation_information" to NVI

**Comment by arnaudon** [comment]
ok, this looks good, thanks! I'll clean it up and merge

**Comment by d-schindler** [comment]
I copied the text for the licence from Leiden Repo, not sure if this is ok

**Comment by arnaudon** [comment]
Thanks, yes, licence should be fine!

**Pull request merged**
