### PR TITLE
Compute matrix exponential via spectral decomposition

### LINKED ISSUE #66: Alternative ways to compute matrix exponential
As pointed out in the code, we might be able to come up with better ways to compute matrix exponentials **repeatedly**: https://github.com/barahona-research-group/PyGenStability/blob/54f7358ec585fa8b18c26f3984f0107fa3351d58/src/pygenstability/constructors.py#L37

### PR DESCRIPTION
**Pull request by d-schindler**
This PR is to resolve #66

### CODE REVIEW

**Comment by d-schindler** [comment]
I've implemented a general structure for pre-computing the spectral decomposition and then using it for computing the matrix exponential. I also started to implement it for the continuous combinatorial constructor. When you are happy with this, it's easy to do this with the others.

First experiments are quite impressive. I ran the MS analysis with continuous combinatorial in Example_2 with both options:

- precomputing the constructors as usual took 50s
- precomputing the constructors using spectral decomposition took less than 1s

Although one can surely optimise the way I compute the (full) spectral decomposition, this seems to work very well, as @michaelschaub and @mauriciobarahona anticipated.

**Comment by d-schindler** [comment]
It would be good to apply the benchmarking to both options. @arnaudon , can you have a look at my code?

**Comment by d-schindler** [comment]
I think eigen decomposition in the directed case needs to be used with caution because we don't have the guarantee (as with symmetric graphs) that we obtain a diagonalisation but only a solution to a generalised eigen decomposition that might lead to large approximation errors in matrix exponential. Not completely sure about this. I added a warning.

**Comment by d-schindler** [comment]
In the benchmarking get_constructor_data seems also to speed up significantly (I only tested for SBM) but I can't produce the final figures because I get the following error: _qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""_

@arnaudon , could you have a look at the benchmarking? - maybe we want to update the figure in the paper because it will look better if faster?

**Comment by d-schindler** [comment]
After installing qt6-wayland it still doesn't work, so I can't do the benchmarking atm. Could somebody else do it?

Also @peach-lucien mentioned that it would be good to do a benchmarking of Leiden, as well.

**Comment by arnaudon** [comment]
Ah sorry, I'm behind on that now, let me catch up this afternoon!

**Comment by d-schindler** [comment]
Great, thank you Alexis! The last two commits are just general improvements..

**Comment by d-schindler** [comment]
I also set computation of exponential via eigen decomposition as a default because it seems much quicker. But this does only affect the combinatorial and normalised contructors (the others don't involve exp and directed is excluded for the moment, see above).

**Comment by d-schindler** [comment]
@arnaudon, let me know if I should do anything else for you to merge after

**Comment by d-schindler** [comment]
there was actually a bug in the timing that is fixed now, will produce the benchmarking plot now

**Comment by d-schindler** [comment]
I've finished the benchmarking and updated the figure in our paper. As expected, the matrix exponential computation implemented here improves things a lot.

**Comment by arnaudon** [comment]
Really cool @d-schindler ! Let me know if my small fix are ok, then I'll merge! coverage should still be at 100 (codecov is not yet up as I write, it's a bit slow for some reason)

**Review by arnaudon — APPROVED** [review]

**Comment by arnaudon** [comment]
so I put spectral by default, except for directed, updated all notebooks and added an option to plot the optimal partitions

**Comment by d-schindler** [comment]
Looks great! I guess we are ready to merge now?

**Pull request merged**
